# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  timeout:  5000
  pool: 5000

development:
  <<: *default
  database: GifTravel_development

test:
  <<: *default
  database: GifTravel_test

production:
  <<: *default
  database: GifTravel_production
  username: GifTravel
  password: <%= ENV['GIFTRAVEL_DATABASE_PASSWORD'] %>
